name: Minimalism by Sarah E Broome
favicon: null
layout_spectrum: 0.30229511042125523
typography_spectrum: 0.361932568019256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313131'
    - '#d5c5ab'
    - '#c1a077'
    - '#7e7c66'
    - '#6d573b'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
