name: Minimalism by Sarah E Broome
favicon: null
layout_spectrum: 0.5440387
typography_spectrum: 0.2669173
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Simple Minimal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313131'
    - '#d5c5ab'
    - '#c1a077'
    - '#7e7c66'
    - '#6d573b'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
