layout_spectrum: 0.5440387
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#313131'
    - '#d5c5ab'
    - '#c1a077'
    - '#7e7c66'
    - '#6d573b'
  lightness: 0
typography_spectrum: 0.2669173
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Minimalism by Sarah E Broome
